CREATE TABLE customer (
  id INT(8) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  Name VARCHAR(30) NOT NULL,
  identification VARCHAR(20) NOT NULL,
  celular VARCHAR(15) NOT NULL,
  correo VARCHAR(40) NOT NULL
);
